FROM maven:3.2.0-eclipse-temurin-21 AS build

COPY src /backend/src

COPY pom.xml /backend

WORKDIR /
RUN mvn clean install -U

FROM openjdk:21
COPY --from=build /backend/target/backend-0.0.1-SNAPSHOT.jar /backend/backend.jar

WORKDIR /backend

EXPOSE 8080

CMD ["java", "-jar", "backend.jar"]