version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Narendra@100178
      MYSQL_DATABASE: shaadi
      MYSQL_USER: Narendra
      MYSQL_PASSWORD: Narendra@100178
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shaadi
      SPRING_DATASOURCE_USERNAME: Narendra
      SPRING_DATASOURCE_PASSWORD: Narendra@100178
    depends_on:
      - mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data:
